PartitionedArrays/PartitionedArrays.jl

src/Interfaces.jl
test/test_fdm.jl

Hi @fverdugo, 
please review this PR when you have time. 
I think there is a miss implementation in one of the outer constructors of PRange that unintentionally leads to harm to parallel scalability. 
Let us see if the tests pass before ...

Fixing the implementation of a PRange outer constructor

---

src/Interfaces.jl
test/test_interfaces.jl

By default the error is deactivated and can be manually activated
by setting PartitionedArrays.ERROR_DISCOVER_PARTS_SND[] = true

Converting the warning on discover parts send into an error

---

src/PTimers.jl
src/PartitionedArrays.jl
test/test_p_timers.jl

Adding optional barriers to tic!

---

src/Interfaces.jl

```
Internal Error: MethodError: propertynames(::PSparseMatrix{Float64, MPIData{SparseArrays.SparseMatrixCSC{Float64, Int64}, 1}, PRange{MPIData{IndexRange, 1}, Exchanger{MPIData{Vector{Int32}, 1}, MPIData{Table{Int32}, 1}}, Nothing}, PRange{MPIData{IndexRange, 1}, Exchanger{MPIData{Vector{Int32}, 1}, MPIData{Table{Int32}, 1}}, Nothing}, Exchanger{MPIData{Vector{Int32}, 1}, MPIData{Table{Int64}, 1}}}, ::Bool) is ambiguous. Candidates:
propertynames(x, private::Bool) in Base at reflection.jl:1581
propertynames(x::PSparseMatrix, private) in PartitionedArrays at /home/amartinh/.julia/packages/PartitionedArrays/YgsH7/src/Interfaces.jl:2007
Possible fix, define
propertynames(::PSparseMatrix, ::Bool)
```

Avoids the following error message

---

src/Interfaces.jl

Hi @fverdugo, the division operation between `number` and `PVector` is not implemented. I'm not sure if the proposed solution is the most efficient, though.

added :/ operation between number and Pvector

---

src/MPIBackend.jl

I have accidentally hit this multiple times, and it is pretty confusing when you get a "not implemented error", so I suggest to spell out the reason in the error message.

Enhance error message for mismatch between MPI processes and number of parts.

---

Project.toml
test/mpi/mpiexec.jl

Would be nice to have a new release which doesn't restrict to MPI.jl < 0.20.

Update MPI compat and set version to 0.2.11.

---

docs/src/usage.md
src/Interfaces.jl
src/MPIBackend.jl
src/PartitionedArrays.jl
src/SequentialBackend.jl
test/mpi/driver_exception.jl
test/mpi/driver_fdm.jl
test/mpi/driver_fem_sa.jl
test/mpi/driver_interfaces.jl
test/mpi/driver_mpi_backend.jl
test/mpi/driver_p_timers.jl
test/sequential/FDMTests.jl
test/sequential/FEMSATests.jl
test/sequential/InterfacesTests.jl
test/sequential/PTimersTests.jl
test/sequential/SequentialBackendTests.jl

- Do not use constants `sequental` and `mpi` anymore. Use `SequentalBackend()` and `MPIBackend()` instead. Main reason: Having global constants written in lower case letters is not a good idea.
-  prun is renamed to with_backend
- Old syntax is still working, but with deprecation warnings.
Example:
OLD
```julia
prun(mpi,np) do parts
end
```
NEW
```julia
with_backend(MPIBackend(),np) do parts
end
```
cc @amartinhuertas @fredrikekre @termi-official

Misc syntax improvements with respect to the usage of backends

---

src/Interfaces.jl

This causes a warning when compiling the package:
```
WARNING: method definition for async_exchange! at C:\Users\olavm\.julia\packages\PartitionedArrays\g9b74\src\Interfaces.jl:857 declares type variable Tsnd but does not use it.
```
To be honest, also `Trcv` looks useless (but at least it's referenced in the method signature).
Spotted in https://github.com/fredrikekre/HYPRE.jl/issues/11#issue-1523729138

Remove unused type parameter in method definition

---

src/MPIBackend.jl

This PR closes issue #89 . 
_get_parts_ids_body() was accessing MPI.API, a module introduced on MPI.jl v0.20. Introduced switch that restores compatibility with older versions of MPI.jl.
Now all the tests run with MPI v0.19.2.

Bugfix: fixed compat issues with MPI.jl v0.19

---

src/MPIBackend.jl
test/mpi/InterfacesTests.jl

`with_backend` now works as intended in PR #87 .
When running a program in a subcommunicator, `with_backend` only runs the driver on the subcommunicator (instead of the whole COMM_WORLD).

Bugfix: Executing programs within a subcommunicator of COMM_WORLD

---

src/primitives.jl

s.t. the eltype of the returned array is not Any in the case there are no outgoing neighbors

Fix in fix_in_exchangeGraph_impl 

---

src/debug_array.jl
src/mpi_array.jl

Redesigning the signatures of with_mpi(f,...) and with_debug(f,...) such that they now allow the user to pass args... and kwargs... to the f function. This is useful, e.g., to pass info about the layout of the process grid from GridapDistributed

Generalizing with_debug() and with_mpi() functions

---

src/p_sparse_matrix.jl
src/p_vector.jl

This patch adds references to the index mapping functions from the function `local_values`, `own_values`, `ghost_values`, `own_ghost_values`, and `ghost_own_values`.

Add some docstring cross references

---

CHANGELOG.md
src/p_sparse_matrix.jl

This PR implements things dicussed in #115 . 
Notably, it adds a new kw-argument `discover_cols=true` to the method `psparse!`, which allows the user to turn off column-index discovery.

Using LocalIndices with psparse! constructors

---

CHANGELOG.md
src/p_sparse_matrix.jl
test/p_sparse_matrix_tests.jl

Hi @fverdugo , could you have a look at this? 
A concern: 
I've commented the test for 
```julia
Base.similar(::Type{<:PSparseMatrix{V}},inds::Tuple{<:PRange,<:PRange}) where V
```
This signature does not work, but it's not our issue. The problem comes from `SparseArrays.jl`, which only provides an [undefined constructor](https://github.com/JuliaSparse/SparseArrays.jl/blob/18b7fcefa18098d2c1752431d1c6fc656b44b888/src/sparsematrix.jl#L55) with signature 
```julia
SparseMatrixCSC{Tv,Ti}(::UndefInitializer, m::Integer, n::Integer) where {Tv, Ti}
```
whereas `Base.similar` calls 
```julia
SparseMatrixCSC{Tv,Ti}(::UndefInitializer, s::Tuple{Integer,Integer}) where {Tv, Ti}
```
I guess we should open an issue in `SparseArrays.jl`, but I've [commented the …

Bugfix: `Base.similar` for `PSparseMatrix`

---

src/p_sparse_matrix.jl

I assume this is a typo. Very minor thing.

Fixed typo

---

src/p_sparse_matrix.jl
src/sparse_utils.jl
test/p_sparse_matrix_tests.jl

This PR improves matrix assembly by reducing memory footprint, based on my thesis ‘Efficient Algorithm for Large-scale Matrix Assembly’.

add matrix_assembly! and precompute_nzindex!

---

README.md

Fixes #185 
This adds a Zenodo DOI badge to the README. There is currently no actual zenodo DOI, since we need to make a release to get one. However, I have used the git repo id (from inspecting <https://api.github.com/repos/PartitionedArrays/PartitionedArrays.jl>) in the badge link, so it should start rendering the latest DOI once we tag a release.

Add DOI badge for Zenodo integration

---

src/PartitionedArrays.jl
src/mpi_array.jl
src/p_vector.jl
src/primitives.jl
test/p_vector_tests.jl

This PR adds new non_blocking_dot functions and their relevant setup, non_blocking_reduction and non_blocking_reduction_impl functions for MPIArray, and a default primitive version for DebugArray. There is a small quick test included as well. 
Let me know if anything else must be added!

Non-blocking allReduce implementation for dot products

---

.github/workflows/ci.yml
README.md

This fixes the error in the cache action (503 return code from cache server every time). It doesn't speed up the CI like the change in https://github.com/GalerkinToolkit/GalerkinToolkit.jl/pull/212 but it's still a good idea to apply the fix.

Investigate cache miss in CI
